include: package:very_good_analysis/analysis_options.3.0.1.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false
  exclude:
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    require_trailing_commas: true
    constant_identifier_names: false
    use_super_parameters: true
